### ISSUE TITLE
boolean ClassCastException in ConstraintTransformerJpaImpl

### ISSUE THREAD

**Issue by ngonzalezpazFC** [AppJars/commons-backend#15]
[This line](https://github.com/AppJars/commons-backend/blob/dbe433ec2977d29e1a4eacf3571a9a95c714e383/commons-data-impl/src/main/java/com/appjars/saturn/dao/jpa/ConstraintTransformerJpaImpl.java#L56) in ConstraintTransformerJpaImpl throws  ClassCastException because it recieves `boolean` instead of `Boolean`.

**Comment by javier-godoy** [comment]
Good catch. I need to perform a boxing conversion before checking.

**Comment by javier-godoy** [comment]
This should be fixed in #16. Can you give it a look?
