### ISSUE TITLE
Validations API enhancement discussion

### ISSUE THREAD

**Issue by ngonzalezpazFC** [AppJars/commons-backend#20]
So far, to implement validations, the user must define and retrieve a list of validators (`List<Validator<T>>`), casting each validation to the right validation type for it to get applied on the desired method.

E.g. a validation defined in the LanguageService of I18nManager project:
```	
public List<Validator<LanguageDto>> getValidators() {
	return Arrays.asList((CreationValidator<LanguageDto>) (lDto -> {
		if (findByLanguageKey(lDto.getLanguageKey()).isPresent()) {
			return Arrays.asList(new ErrorDescription("This language is already created"));
		}
		return Validator.success();
	}));
}
```

This works, but maybe if the user wants to do several validations, and for each service method that supports this validations, the code could become long and hard to read.
Maybe some enhancements to the validations definitions could be made.

**Comment by javier-godoy** [comment]
Moreover, there is risk of writing:

```
public List<Validator<LanguageDto>> getValidators() {
	return Arrays.asList( dto -> {
		if (findByLanguageKey(dto.getLanguageKey()).isPresent()) {
			return Arrays.asList(new ErrorDescription("This language is already created"));
		}
		return Validator.success();
	}));
}
```

which is _obviously_ wrong (the proof is left as an exercise for the reader).

**Comment by javier-godoy** [comment]
A validator returns sucess if a condition holds, and a (likely one-element) collection of errors otherwise.

Therefore, instead of:
```
if (findByLanguageKey(dto.getLanguageKey()).isPresent()) {
   return Arrays.asList(new ErrorDescription("This language is already created"));
}
return Validator.success();
```

we can provide a builder method that can be used as:
```
Validator.forCondition(
   dto->!findByLanguageKey(dto.getLanguageKey()).isPresent(), // the condition
   ()->new ErrorDescription("This language is already created")  // the error supplier
 );
 ```

**Comment by javier-godoy** [comment]
Furthermore, there should be a simple (non-redundant, boilerplate free) way of adding a validator that executes both on creation and update.

**Comment by mlopezFC** [comment]
Yes, the first thing that pops into my mind is that we could provide a list of enums that represents each of the CRUD stages that this validator should apply as an extra parameter for the `forCondition()` method.

**Comment by javier-godoy** [comment]
(1) Validators that do not implement any sub-interface of Validator must always be executed. (If it's not the desired behavior, then it's your responsability to specify the validator kind).

(2) Each sub-interface will have it's own `forCondition` method, so that `CreationValidator.forCondition` will return a `CreationValidator` and `DeletionValidator.forCondition` will return a `DeletionValidator`.

(3) Instead of enums, which are non-extensible, we can define a `Validatable` interface and a `ValidationKind` enum that implements that interface. Coupled with (1) this means that one only needs to specify the validator kind when implementing mixed services (such as CrudService)

```
Validator
.on(ValidationKind.CREATE, ValidationKind.UPDATE)
.forCondition(
   dto->!findByLanguageKey(dto.getLanguageKey()).isPresent(), // the condition
   ()->new ErrorDescription("This language is already created"),  // the error supplier
   UpdateValidator.class, CreateValidator.class
 );
```
