### ISSUE TITLE
Remove type parameter from QuerySpec

### ISSUE THREAD

**Issue by javier-godoy** [AppJars/commons-backend#31]
```diff
- QuerySpec<K extends Serializable>
+ QuerySpec
```

This is a breaking change.

**Comment by mlopezFC** [comment]
Maybe instead of K meaning a key, we could use T meaning an entity, that might be useful to avoid a lot of castings.

**Comment by javier-godoy** [comment]
Note that no castings are involved because `QuerySpec` is not typed (fields are referenced as string).

What would be the signature of this method?
https://github.com/AppJars/commons-backend/blob/cc07f0892e0ca613803036fb2d639e47ce522ce9/commons-business-impl/src/main/java/com/appjars/saturn/service/ConversionQueryServiceMixin.java#L61

with

https://github.com/AppJars/commons-backend/blob/cc07f0892e0ca613803036fb2d639e47ce522ce9/commons-business-impl/src/main/java/com/appjars/saturn/service/ConversionQueryServiceMixin.java#L39-L43

The DAO will expect `QuerySpec<P>` but we cannot have ` List<B> filter(QuerySpec<P>)` in the service layer (because the view cannot* be required to care about the type of persistence layer entity).
