### ISSUE TITLE
UpdateService interface generic types

### ISSUE THREAD

**Issue by ngonzalezpazFC** [AppJars/commons-backend#32]
UpdateService interface is declared with generic types T,K: `public interface UpdateService<T, K>` but K type is not used.
Should it be removed or it is it is useful to keep a relation with `CreationService<T, K>` whos method save returns the `K` id type, for example? Or with other interfaces that extend `UpdateService`?
I stumbled upon this doubt because `DeletionService<T>` delete method returns void as the update method, but is declared only with `<T>`.

**Comment by javier-godoy** [comment]
> Should it be removed?

Yes.
https://github.com/AppJars/commons-backend/blob/28cd8c9cd40371e2de7a2ecf15d12abeb027729e/commons-business/src/main/java/com/appjars/saturn/service/UpdateService.java#L30-L34
