### ISSUE TITLE
Should Identifiable be immutable?

### ISSUE THREAD

**Issue by javier-godoy** [AppJars/commons-backend#41]
According to the javadoc, an `Identifiable` "represents an object that can be identified". There exist identifiable things that are immutable. The interface, however, has a `setId` method.

**Comment by mlopezFC** [comment]
Yes, good point.
For what I'm able to see, we're not using `setId()` anywhere, so we should be able to remove it without causing any harm.

**Comment by javier-godoy** [comment]
LGTM, let's do it.

**Comment by ngonzalezpazFC** [comment]
In the SIGAF project I am using setId given that they increment the id value manually in the code

**Comment by javier-godoy** [comment]
> In the SIGAF project I am using setId given that they increment the id value manually in the code

I understand the project uses `setId` from `BaseEntity`, but not directly from `Identifiable`.

**Comment by ngonzalezpazFC** [comment]
> 
> 
> > In the SIGAF project I am using setId given that they increment the id value manually in the code
> 
> I understand the project uses `setId` from `BaseEntity`, but not directly from `Identifiable`.

Yes, you are right.
