### ISSUE TITLE
Expose validators to the presentation layer

### ISSUE THREAD

**Issue by javier-godoy** [AppJars/commons-backend#52]
From the presentation layer I want to run service validations _before_ actually saving an item, so that I'm able to display validation errors  in advance.

**Comment by ngonzalezpazFC** [comment]
This feature could be really useful to, as you said, present errors to the user in a nice way.
It could be helpful that the validation mechanism could return a list of validation errors like services that implement `ValidationSupport `does, but I can't see where the validations should be triggered.

**Comment by javier-godoy** [comment]
> I can't see where the validations should be triggered.

If you are using Binder, they can be bean-level validation with `Binder`. Otherwise, just call the validation when you see fit, and you'll known whether the bean is _valid_ (e.g. if it's "insertable") without actually invoking the service operation.

**Comment by ngonzalezpazFC** [comment]
That is a good option if Vaadin is being used, but my comment was pointed to that Commons Backend can be used with a different frontend technology
