### ISSUE TITLE
ValidationSupport to throw specific Exceptions

### ISSUE THREAD

**Issue by ngonzalezpazFC** [AppJars/commons-backend#55]
> > I think I can store the validation class name in the field attribute
> 
> Why do you need the validation class name?

I thought of using the name of the class instead of using random strings, but given that the vaadin module does not have dependency of business-impl and cannot see the validators classes, I will use the following strings:
- creation
- deletion
- update

_Originally posted by @ngonzalezpazFC in https://github.com/AppJars/commons-backend/issues/37#issuecomment-889075848_

The comment quoted is related to this issue. I was thinking that each kind of CRUD validation could throw a specific exception, i.e CreationValidationException, UpdateValidationException, so as the presentation layer can display a more specific  message, or in my case to configure ErrorWindowAddon to show a specific message once it catches each Exception type, instead of a generic ValidationException message.

**Comment by javier-godoy** [comment]
It seems a good idea. There are not many places in commons-backend where we throw that exception.
